import type {
  Provider,
  Service,
  ServiceRequest,
  ChatConversation,
  ChatMessage,
  Review,
  DashboardMetrics,
  SubscriptionTier,
  BrowseService,
  ClientContractedService,
  ClientProfile,
  AppNotification,
} from "./types"

export const currentProvider: Provider = {
  id: "p1",
  name: "Carlos Martinez",
  email: "carlos@hughelp.co",
  phone: "+57 310 456 7890",
  avatar: "",
  bio: "Plomero profesional con mas de 10 anos de experiencia. Especializado en instalaciones y reparaciones residenciales.",
  rating: 4.8,
  totalReviews: 127,
  verified: true,
  plan: "premium",
  verificationStatus: "approved",
  joinedDate: "2024-03-15",
  servicesCount: 5,
  completedServices: 89,
}

export const services: Service[] = [
  {
    id: "s1",
    title: "Reparacion de tuberias",
    category: "Plomeria",
    description:
      "Reparacion profesional de tuberias de agua y desague. Incluye diagnostico, mano de obra y materiales basicos.",
    price: 85000,
    images: ["/services/reparacion-tuberias.jpg"],
    active: true,
    rating: 4.9,
    totalReviews: 42,
    createdAt: "2024-06-10",
  },
  {
    id: "s2",
    title: "Instalacion de griferias",
    category: "Plomeria",
    description:
      "Instalacion de griferias nuevas en cocina y bano. Garantia de 6 meses sobre la instalacion.",
    price: 65000,
    images: ["/services/instalacion-griferias.jpg"],
    active: true,
    rating: 4.7,
    totalReviews: 28,
    createdAt: "2024-07-22",
  },
  {
    id: "s3",
    title: "Destape de caneria",
    category: "Plomeria",
    description:
      "Servicio de destape de canerias con equipo profesional. Rapido y eficiente.",
    price: 50000,
    images: ["/services/destape-caneria.jpg"],
    active: true,
    rating: 4.8,
    totalReviews: 35,
    createdAt: "2024-08-05",
  },
  {
    id: "s4",
    title: "Revision de sistema hidraulico",
    category: "Plomeria",
    description:
      "Revision completa del sistema hidraulico de su hogar. Reporte detallado incluido.",
    price: 120000,
    images: ["/services/revision-hidraulica.jpg"],
    active: false,
    rating: 4.6,
    totalReviews: 12,
    createdAt: "2024-09-18",
  },
  {
    id: "s5",
    title: "Instalacion de calentador",
    category: "Plomeria",
    description:
      "Instalacion profesional de calentadores de agua. Gas o electrico.",
    price: "negotiable",
    images: ["/services/instalacion-calentador.jpg"],
    active: true,
    rating: 5.0,
    totalReviews: 10,
    createdAt: "2024-10-01",
  },
]

export const serviceRequests: ServiceRequest[] = [
  {
    id: "r1",
    clientName: "Maria Lopez",
    clientAvatar: "",
    serviceTitle: "Reparacion de tuberias",
    description:
      "Tengo una fuga de agua en el bano principal. La tuberia debajo del lavamanos esta goteando constantemente.",
    images: [
      "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=400&h=300&fit=crop",
      "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop",
    ],
    status: "pending",
    date: "2025-02-10",
    time: "10:00 AM",
    location: "Calle 45 #12-30, Bogota",
    locationLat: 4.6486,
    locationLng: -74.0628,
    preferredDates: ["2025-02-10", "2025-02-12", "2025-02-15"],
    createdAt: "2025-02-07",
  },
  {
    id: "r2",
    clientName: "Juan Perez",
    clientAvatar: "",
    serviceTitle: "Destape de caneria",
    description:
      "La caneria de la cocina esta tapada. El agua no drena desde hace 2 dias.",
    images: [
      "https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=400&h=300&fit=crop",
    ],
    status: "pending",
    date: "2025-02-11",
    time: "2:00 PM",
    location: "Carrera 7 #89-15, Bogota",
    locationLat: 4.6580,
    locationLng: -74.0560,
    preferredDates: ["2025-02-11", "2025-02-13"],
    createdAt: "2025-02-07",
  },
  {
    id: "r3",
    clientName: "Ana Garcia",
    clientAvatar: "",
    serviceTitle: "Instalacion de griferias",
    description:
      "Necesito cambiar la griferia del bano. Ya tengo la griferia nueva, solo necesito instalacion.",
    images: [
      "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&h=300&fit=crop",
    ],
    status: "accepted",
    date: "2025-02-09",
    time: "9:00 AM",
    location: "Avenida 68 #23-45, Bogota",
    locationLat: 4.6350,
    locationLng: -74.0830,
    preferredDates: ["2025-02-09"],
    createdAt: "2025-02-05",
  },
  {
    id: "r4",
    clientName: "Roberto Diaz",
    clientAvatar: "",
    serviceTitle: "Reparacion de tuberias",
    description:
      "Tuberia rota en la pared de la sala. Se necesita abrir la pared para acceder.",
    images: [
      "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop",
      "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=400&h=300&fit=crop",
      "https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=400&h=300&fit=crop",
    ],
    status: "in_progress",
    date: "2025-02-08",
    time: "8:00 AM",
    location: "Calle 100 #50-20, Bogota",
    locationLat: 4.6866,
    locationLng: -74.0486,
    preferredDates: ["2025-02-08"],
    createdAt: "2025-02-03",
  },
  {
    id: "r5",
    clientName: "Sofia Hernandez",
    clientAvatar: "",
    serviceTitle: "Instalacion de calentador",
    description:
      "Instalacion de calentador de paso a gas. El apartamento es nuevo.",
    images: [],
    status: "completed",
    date: "2025-02-01",
    time: "11:00 AM",
    location: "Carrera 15 #78-90, Bogota",
    locationLat: 4.6690,
    locationLng: -74.0560,
    preferredDates: ["2025-02-01", "2025-02-03"],
    createdAt: "2025-01-28",
  },
  {
    id: "r6",
    clientName: "Pedro Castro",
    clientAvatar: "",
    serviceTitle: "Destape de caneria",
    description: "Caneria del bano principal completamente tapada.",
    images: [],
    status: "completed",
    date: "2025-01-25",
    time: "3:00 PM",
    location: "Calle 72 #10-55, Bogota",
    locationLat: 4.6590,
    locationLng: -74.0680,
    preferredDates: ["2025-01-25"],
    createdAt: "2025-01-22",
  },
]

export const chatConversations: ChatConversation[] = [
  {
    id: "c1",
    participantName: "Roberto Diaz",
    participantAvatar: "",
    lastMessage: "Perfecto, entonces nos vemos manana a las 8am",
    lastMessageTime: "Hace 5 min",
    unreadCount: 2,
    relatedRequestId: "r4",
    relatedServiceTitle: "Reparacion de tuberias",
    relatedRequestStatus: "in_progress",
  },
  {
    id: "c2",
    participantName: "Ana Garcia",
    participantAvatar: "",
    lastMessage: "Ya tengo la griferia lista para la instalacion",
    lastMessageTime: "Hace 1h",
    unreadCount: 0,
    relatedRequestId: "r3",
    relatedServiceTitle: "Instalacion de griferias",
    relatedRequestStatus: "accepted",
  },
  {
    id: "c3",
    participantName: "Maria Lopez",
    participantAvatar: "",
    lastMessage: "Buenos dias, la fuga sigue empeorando",
    lastMessageTime: "Hace 2h",
    unreadCount: 1,
    relatedRequestId: "r1",
    relatedServiceTitle: "Reparacion de tuberias",
    relatedRequestStatus: "pending",
  },
  {
    id: "c4",
    participantName: "Sofia Hernandez",
    participantAvatar: "",
    lastMessage: "Gracias por el excelente servicio!",
    lastMessageTime: "Hace 1d",
    unreadCount: 0,
    relatedRequestId: "r5",
    relatedServiceTitle: "Instalacion de calentador",
    relatedRequestStatus: "completed",
  },
]

export const chatMessages: ChatMessage[] = [
  {
    id: "m1",
    senderId: "client",
    text: "Hola, necesito que venga a revisar una tuberia que esta goteando",
    timestamp: "10:00 AM",
    read: true,
    type: "text",
  },
  {
    id: "m2",
    senderId: "provider",
    text: "Buenos dias! Claro, puedo ir manana por la manana. Que direccion es?",
    timestamp: "10:02 AM",
    read: true,
    type: "text",
  },
  {
    id: "m3",
    senderId: "client",
    text: "Calle 100 #50-20, Bogota. La tuberia esta en la pared de la sala.",
    timestamp: "10:05 AM",
    read: true,
    type: "text",
  },
  {
    id: "m4",
    senderId: "provider",
    text: "Entendido. Necesitare abrir la pared para revisar. Le puedo dar un presupuesto una vez vea el dano.",
    timestamp: "10:08 AM",
    read: true,
    type: "text",
  },
  {
    id: "m5",
    senderId: "client",
    text: "Perfecto, entonces nos vemos manana a las 8am",
    timestamp: "10:10 AM",
    read: false,
    type: "text",
  },
]

export const reviews: Review[] = [
  {
    id: "rev1",
    clientName: "Sofia Hernandez",
    clientAvatar: "",
    rating: 5,
    comment:
      "Excelente servicio! Instalo el calentador rapidamente y dejo todo limpio. Muy profesional.",
    date: "2025-02-01",
    serviceTitle: "Instalacion de calentador",
  },
  {
    id: "rev2",
    clientName: "Pedro Castro",
    clientAvatar: "",
    rating: 5,
    comment:
      "Destape la caneria en menos de una hora. Muy buen precio y excelente atencion.",
    date: "2025-01-25",
    serviceTitle: "Destape de caneria",
  },
  {
    id: "rev3",
    clientName: "Laura Moreno",
    clientAvatar: "",
    rating: 4,
    comment:
      "Buen trabajo en la reparacion. Llego puntual y explico todo el proceso.",
    date: "2025-01-20",
    serviceTitle: "Reparacion de tuberias",
  },
  {
    id: "rev4",
    clientName: "Andres Ruiz",
    clientAvatar: "",
    rating: 5,
    comment:
      "La griferia quedo perfecta. Muy recomendado para instalaciones.",
    date: "2025-01-15",
    serviceTitle: "Instalacion de griferias",
  },
]

export const dashboardMetrics: DashboardMetrics = {
  activeServices: 4,
  pendingRequests: 2,
  completedServices: 89,
  averageRating: 4.8,
  monthlyEarnings: 2450000,
  weeklyActivity: [
    { day: "Lun", requests: 3, completed: 2 },
    { day: "Mar", requests: 5, completed: 4 },
    { day: "Mie", requests: 2, completed: 2 },
    { day: "Jue", requests: 4, completed: 3 },
    { day: "Vie", requests: 6, completed: 5 },
    { day: "Sab", requests: 3, completed: 3 },
    { day: "Dom", requests: 1, completed: 1 },
  ],
}

export const subscriptionTiers: SubscriptionTier[] = [
  {
    id: "basic",
    name: "Basico",
    price: 9990,
    features: [
      "Hasta 3 servicios publicados",
      "Visibilidad estandar",
      "Chat con clientes",
      "Soporte por email",
    ],
    maxServices: 3,
    highlighted: false,
    popular: false,
  },
  {
    id: "premium",
    name: "Premium",
    price: 29990,
    features: [
      "Hasta 10 servicios publicados",
      "Visibilidad destacada",
      "Chat prioritario",
      "Badge verificado",
      "Estadisticas avanzadas",
      "Soporte prioritario",
    ],
    maxServices: 10,
    highlighted: true,
    popular: true,
  },
  {
    id: "enterprise",
    name: "Empresarial",
    price: 59990,
    features: [
      "Servicios ilimitados",
      "Maxima visibilidad",
      "Chat prioritario",
      "Badge verificado + Premium",
      "Estadisticas completas",
      "Soporte dedicado 24/7",
      "Perfil destacado en busqueda",
      "Reportes mensuales",
    ],
    maxServices: -1,
    highlighted: false,
    popular: false,
  },
]

export const providerNotifications: AppNotification[] = [
  {
    id: "n1",
    type: "new_request",
    title: "Nueva solicitud",
    message: "Maria Lopez solicito Reparacion de tuberias",
    time: "Hace 10 min",
    read: false,
    relatedId: "r1",
  },
  {
    id: "n2",
    type: "new_request",
    title: "Nueva solicitud",
    message: "Juan Perez solicito Destape de caneria",
    time: "Hace 30 min",
    read: false,
    relatedId: "r2",
  },
  {
    id: "n3",
    type: "new_message",
    title: "Nuevo mensaje",
    message: "Roberto Diaz te envio un mensaje",
    time: "Hace 1h",
    read: false,
    relatedId: "c1",
  },
  {
    id: "n4",
    type: "new_review",
    title: "Nueva resena",
    message: "Sofia Hernandez te dejo 5 estrellas en Instalacion de calentador",
    time: "Hace 3h",
    read: true,
    relatedId: "rev1",
  },
  {
    id: "n5",
    type: "request_completed",
    title: "Servicio completado",
    message: "Has completado Destape de caneria para Pedro Castro",
    time: "Hace 1d",
    read: true,
    relatedId: "r6",
  },
  {
    id: "n6",
    type: "system",
    title: "Plan Premium activo",
    message: "Tu suscripcion Premium se renueva el 15 de marzo",
    time: "Hace 2d",
    read: true,
  },
  {
    id: "n7",
    type: "request_accepted",
    title: "Solicitud aceptada",
    message: "Aceptaste la solicitud de Ana Garcia para Instalacion de griferias",
    time: "Hace 3d",
    read: true,
    relatedId: "r3",
  },
]

export const serviceCategories = [
  { id: "plumbing", label: "Plomeria", icon: "Wrench" },
  { id: "electrical", label: "Electricidad", icon: "Zap" },
  { id: "cleaning", label: "Limpieza", icon: "Sparkles" },
  { id: "painting", label: "Pintura", icon: "Paintbrush" },
  { id: "carpentry", label: "Carpinteria", icon: "Hammer" },
  { id: "locksmith", label: "Cerrajeria", icon: "KeyRound" },
  { id: "appliances", label: "Electrodomesticos", icon: "Refrigerator" },
  { id: "gardening", label: "Jardineria", icon: "TreePine" },
]

// ==================== CLIENT MOCK DATA ====================

export const clientProfile: ClientProfile = {
  id: "cl1",
  name: "Laura Moreno",
  email: "laura@email.com",
  phone: "+57 315 789 0123",
  avatar: "",
  joinedDate: "2024-05-20",
  totalServicesRequested: 12,
}

export const browseServices: BrowseService[] = [
  {
    id: "bs1",
    title: "Reparacion de tuberias",
    category: "Plomeria",
    description:
      "Reparacion profesional de tuberias de agua y desague. Incluye diagnostico, mano de obra y materiales basicos.",
    price: 85000,
    images: ["/services/reparacion-tuberias.jpg"],
    rating: 4.9,
    totalReviews: 42,
    providerName: "Carlos Martinez",
    providerAvatar: "",
    providerVerified: true,
    providerRating: 4.8,
    distance: "1.2 km",
    location: "Chapinero, Bogota",
    providerLat: 4.6486,
    providerLng: -74.0628,
  },
  {
    id: "bs2",
    title: "Instalacion electrica residencial",
    category: "Electricidad",
    description:
      "Instalacion y reparacion de sistemas electricos residenciales. Certificado RETIE incluido.",
    price: 120000,
    images: ["/services/electricidad-residencial.jpg"],
    rating: 4.7,
    totalReviews: 35,
    providerName: "Andres Ruiz",
    providerAvatar: "",
    providerVerified: true,
    providerRating: 4.7,
    distance: "2.5 km",
    location: "Usaquen, Bogota",
    providerLat: 4.6955,
    providerLng: -74.0313,
  },
  {
    id: "bs3",
    title: "Limpieza profunda del hogar",
    category: "Limpieza",
    description:
      "Servicio completo de limpieza profunda: cocina, banos, pisos, ventanas. Productos incluidos.",
    price: 95000,
    images: ["/services/limpieza-hogar.jpg"],
    rating: 4.8,
    totalReviews: 58,
    providerName: "Diana Torres",
    providerAvatar: "",
    providerVerified: true,
    providerRating: 4.9,
    distance: "0.8 km",
    location: "Suba, Bogota",
    providerLat: 4.7410,
    providerLng: -74.0836,
  },
  {
    id: "bs4",
    title: "Pintura interior de apartamento",
    category: "Pintura",
    description:
      "Pintura profesional de interiores. Incluye preparacion de superficies y dos manos de pintura.",
    price: 180000,
    images: ["/services/pintura-interior.jpg"],
    rating: 4.6,
    totalReviews: 22,
    providerName: "Miguel Sanchez",
    providerAvatar: "",
    providerVerified: false,
    providerRating: 4.5,
    distance: "3.1 km",
    location: "Teusaquillo, Bogota",
    providerLat: 4.6350,
    providerLng: -74.0830,
  },
  {
    id: "bs5",
    title: "Carpinteria a medida",
    category: "Carpinteria",
    description:
      "Muebles y estanterias a medida. Closets, cocinas integrales, repisas flotantes.",
    price: "negotiable",
    images: ["/services/carpinteria.jpg"],
    rating: 4.9,
    totalReviews: 31,
    providerName: "Jorge Ramirez",
    providerAvatar: "",
    providerVerified: true,
    providerRating: 4.8,
    distance: "4.0 km",
    location: "Kennedy, Bogota",
    providerLat: 4.6280,
    providerLng: -74.1510,
  },
  {
    id: "bs6",
    title: "Cerrajeria 24 horas",
    category: "Cerrajeria",
    description:
      "Apertura de puertas, cambio de chapas, instalacion de cerraduras de seguridad.",
    price: 60000,
    images: ["/services/cerrajeria.jpg"],
    rating: 4.5,
    totalReviews: 67,
    providerName: "Felipe Gomez",
    providerAvatar: "",
    providerVerified: true,
    providerRating: 4.6,
    distance: "1.8 km",
    location: "Chapinero, Bogota",
    providerLat: 4.6520,
    providerLng: -74.0580,
  },
  {
    id: "bs7",
    title: "Destape de caneria",
    category: "Plomeria",
    description:
      "Servicio de destape de canerias con equipo profesional. Rapido y eficiente.",
    price: 50000,
    images: ["/services/destape-caneria.jpg"],
    rating: 4.8,
    totalReviews: 35,
    providerName: "Carlos Martinez",
    providerAvatar: "",
    providerVerified: true,
    providerRating: 4.8,
    distance: "1.2 km",
    location: "Chapinero, Bogota",
    providerLat: 4.6500,
    providerLng: -74.0650,
  },
  {
    id: "bs8",
    title: "Instalacion de calentador",
    category: "Plomeria",
    description:
      "Instalacion profesional de calentadores de agua. Gas o electrico.",
    price: "negotiable",
    images: ["/services/instalacion-calentador.jpg"],
    rating: 5.0,
    totalReviews: 10,
    providerName: "Carlos Martinez",
    providerAvatar: "",
    providerVerified: true,
    providerRating: 4.8,
    distance: "1.2 km",
    location: "Chapinero, Bogota",
    providerLat: 4.6470,
    providerLng: -74.0610,
  },
]

export const clientContractedServices: ClientContractedService[] = [
  {
    id: "cs1",
    serviceTitle: "Reparacion de tuberias",
    providerName: "Carlos Martinez",
    providerAvatar: "",
    status: "in_progress",
    date: "2025-02-08",
    time: "8:00 AM",
    location: "Calle 100 #50-20, Bogota",
    price: 85000,
    rated: false,
    providerLat: 4.6486,
    providerLng: -74.0628,
  },
  {
    id: "cs2",
    serviceTitle: "Limpieza profunda del hogar",
    providerName: "Diana Torres",
    providerAvatar: "",
    status: "accepted",
    date: "2025-02-10",
    time: "9:00 AM",
    location: "Carrera 15 #78-90, Bogota",
    price: 95000,
    rated: false,
    providerLat: 4.7410,
    providerLng: -74.0836,
  },
  {
    id: "cs3",
    serviceTitle: "Instalacion electrica residencial",
    providerName: "Andres Ruiz",
    providerAvatar: "",
    status: "pending",
    date: "2025-02-12",
    time: "2:00 PM",
    location: "Avenida 68 #23-45, Bogota",
    price: 120000,
    rated: false,
    providerLat: 4.6955,
    providerLng: -74.0313,
  },
  {
    id: "cs4",
    serviceTitle: "Destape de caneria",
    providerName: "Carlos Martinez",
    providerAvatar: "",
    status: "completed",
    date: "2025-01-25",
    time: "3:00 PM",
    location: "Calle 72 #10-55, Bogota",
    price: 50000,
    rated: true,
    providerLat: 4.6486,
    providerLng: -74.0628,
  },
  {
    id: "cs5",
    serviceTitle: "Cerrajeria 24 horas",
    providerName: "Felipe Gomez",
    providerAvatar: "",
    status: "completed",
    date: "2025-01-15",
    time: "7:00 PM",
    location: "Calle 45 #12-30, Bogota",
    price: 60000,
    rated: false,
    providerLat: 4.6520,
    providerLng: -74.0580,
  },
  {
    id: "cs6",
    serviceTitle: "Pintura interior de apartamento",
    providerName: "Miguel Sanchez",
    providerAvatar: "",
    status: "completed",
    date: "2025-01-10",
    time: "8:00 AM",
    location: "Carrera 7 #89-15, Bogota",
    price: 180000,
    rated: true,
    providerLat: 4.6350,
    providerLng: -74.0830,
  },
]

export const clientChatConversations: ChatConversation[] = [
  {
    id: "cc1",
    participantName: "Carlos Martinez",
    participantAvatar: "",
    lastMessage: "Perfecto, llego manana a las 8am",
    lastMessageTime: "Hace 5 min",
    unreadCount: 1,
    relatedRequestId: "cs1",
    relatedServiceTitle: "Reparacion de tuberias",
    relatedRequestStatus: "in_progress",
  },
  {
    id: "cc2",
    participantName: "Diana Torres",
    participantAvatar: "",
    lastMessage: "Llevo todos los productos necesarios",
    lastMessageTime: "Hace 30 min",
    unreadCount: 0,
    relatedRequestId: "cs2",
    relatedServiceTitle: "Limpieza profunda del hogar",
    relatedRequestStatus: "accepted",
  },
  {
    id: "cc3",
    participantName: "Andres Ruiz",
    participantAvatar: "",
    lastMessage: "Le confirmo disponibilidad para el viernes",
    lastMessageTime: "Hace 2h",
    unreadCount: 1,
    relatedRequestId: "cs3",
    relatedServiceTitle: "Instalacion electrica residencial",
    relatedRequestStatus: "pending",
  },
]
